[2025-08-18T18:58:19.463+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-17T00:00:00+00:00 [queued]>
[2025-08-18T18:58:19.473+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-17T00:00:00+00:00 [queued]>
[2025-08-18T18:58:19.474+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-18T18:58:19.490+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_pull_data> on 2025-08-17 00:00:00+00:00
[2025-08-18T18:58:19.496+0000] {standard_task_runner.py:60} INFO - Started process 216 to run task
[2025-08-18T18:58:19.500+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_pull_data', 'scheduled__2025-08-17T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpwv6ex4a9']
[2025-08-18T18:58:19.503+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask dvc_pull_data
[2025-08-18T18:58:19.565+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-17T00:00:00+00:00 [running]> on host bc8ef99d762a
[2025-08-18T18:58:19.644+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-17T00:00:00+00:00'
[2025-08-18T18:58:19.646+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T18:58:19.647+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd C:\\Users\\ymaner069\\OneDrive - Comcast\\GitRepos\\Customer_Churn_Prediction_Pipeline && dvc pull --force']
[2025-08-18T18:58:19.656+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T18:58:19.657+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: too many arguments
[2025-08-18T18:58:19.658+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T18:58:19.669+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T18:58:19.674+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_churn_pipeline, task_id=dvc_pull_data, execution_date=20250817T000000, start_date=20250818T185819, end_date=20250818T185819
[2025-08-18T18:58:19.689+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task dvc_pull_data (Bash command failed. The command returned a non-zero exit code 1.; 216)
[2025-08-18T18:58:19.715+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-18T18:58:19.748+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T20:26:48.891+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-17T00:00:00+00:00 [queued]>
[2025-08-18T20:26:48.904+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-17T00:00:00+00:00 [queued]>
[2025-08-18T20:26:48.905+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-18T20:26:48.926+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_pull_data> on 2025-08-17 00:00:00+00:00
[2025-08-18T20:26:48.934+0000] {standard_task_runner.py:60} INFO - Started process 210 to run task
[2025-08-18T20:26:48.941+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_pull_data', 'scheduled__2025-08-17T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmppflcndhm']
[2025-08-18T20:26:48.948+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask dvc_pull_data
[2025-08-18T20:26:49.047+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-17T00:00:00+00:00 [running]> on host 2e4674d7276b
[2025-08-18T20:26:49.171+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-17T00:00:00+00:00'
[2025-08-18T20:26:49.173+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T20:26:49.176+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && dvc pull --force']
[2025-08-18T20:26:49.189+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T20:26:56.678+0000] {subprocess.py:93} INFO - No remote provided and no default remote set.
[2025-08-18T20:26:56.680+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-18T20:26:56.835+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-18T20:26:56.908+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=dvc_pull_data, execution_date=20250817T000000, start_date=20250818T202648, end_date=20250818T202656
[2025-08-18T20:26:56.993+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-18T20:26:57.077+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
