[2025-08-19T17:39:02.086+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-19T17:38:59.420994+00:00 [queued]>
[2025-08-19T17:39:02.130+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-19T17:38:59.420994+00:00 [queued]>
[2025-08-19T17:39:02.131+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-19T17:39:02.270+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_pull_data> on 2025-08-19 17:38:59.420994+00:00
[2025-08-19T17:39:02.347+0000] {standard_task_runner.py:60} INFO - Started process 723 to run task
[2025-08-19T17:39:02.358+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_pull_data', 'manual__2025-08-19T17:38:59.420994+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpmxms8803']
[2025-08-19T17:39:02.393+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask dvc_pull_data
[2025-08-19T17:39:02.703+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-19T17:38:59.420994+00:00 [running]> on host dc08f7cf7bac
[2025-08-19T17:39:02.914+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T17:38:59.420994+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T17:38:59.420994+00:00'
[2025-08-19T17:39:02.917+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-19T17:39:02.924+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && dvc pull --allow-missing || echo "DVC pull completed with missing files - continuing"']
[2025-08-19T17:39:02.960+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T17:39:15.840+0000] {subprocess.py:93} INFO - WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
[2025-08-19T17:39:15.842+0000] {subprocess.py:93} INFO - md5: bddbedfa515218f2093aa5540131d157
[2025-08-19T17:39:15.876+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - Can't remove the following unsaved files without confirmation. Use `--force` to force.
[2025-08-19T17:39:15.877+0000] {subprocess.py:93} INFO - /opt/***/Customer_Churn_Prediction_Pipeline/models/churn_model.pkl
[2025-08-19T17:39:16.191+0000] {subprocess.py:93} INFO - DVC pull completed with missing files - continuing
[2025-08-19T17:39:16.192+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T17:39:16.252+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=dvc_pull_data, execution_date=20250819T173859, start_date=20250819T173902, end_date=20250819T173916
[2025-08-19T17:39:16.317+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-19T17:39:16.377+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
