[2025-08-19T17:45:41.681+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-19T17:45:38.225122+00:00 [queued]>
[2025-08-19T17:45:41.716+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-19T17:45:38.225122+00:00 [queued]>
[2025-08-19T17:45:41.721+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-19T17:45:41.762+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_pull_data> on 2025-08-19 17:45:38.225122+00:00
[2025-08-19T17:45:41.775+0000] {standard_task_runner.py:60} INFO - Started process 883 to run task
[2025-08-19T17:45:41.781+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_pull_data', 'manual__2025-08-19T17:45:38.225122+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpj9tvs89z']
[2025-08-19T17:45:41.789+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask dvc_pull_data
[2025-08-19T17:45:41.882+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_pull_data manual__2025-08-19T17:45:38.225122+00:00 [running]> on host dc08f7cf7bac
[2025-08-19T17:45:42.038+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T17:45:38.225122+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T17:45:38.225122+00:00'
[2025-08-19T17:45:42.047+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-19T17:45:42.049+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && dvc pull --allow-missing || echo "DVC pull completed with missing files - continuing"']
[2025-08-19T17:45:42.074+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T17:45:50.116+0000] {subprocess.py:93} INFO - WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
[2025-08-19T17:45:50.118+0000] {subprocess.py:93} INFO - md5: bddbedfa515218f2093aa5540131d157
[2025-08-19T17:45:50.171+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - Can't remove the following unsaved files without confirmation. Use `--force` to force.
[2025-08-19T17:45:50.172+0000] {subprocess.py:93} INFO - /opt/***/Customer_Churn_Prediction_Pipeline/models/churn_model.pkl
[2025-08-19T17:45:50.449+0000] {subprocess.py:93} INFO - DVC pull completed with missing files - continuing
[2025-08-19T17:45:50.451+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T17:45:50.509+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=dvc_pull_data, execution_date=20250819T174538, start_date=20250819T174541, end_date=20250819T174550
[2025-08-19T17:45:50.576+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-19T17:45:50.636+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
