[2025-08-20T17:47:24.342+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T17:47:24.381+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-19T00:00:00+00:00 [queued]>
[2025-08-20T17:47:24.382+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-20T17:47:24.463+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dvc_pull_data> on 2025-08-19 00:00:00+00:00
[2025-08-20T17:47:24.492+0000] {standard_task_runner.py:60} INFO - Started process 207 to run task
[2025-08-20T17:47:24.531+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'dvc_pull_data', 'scheduled__2025-08-19T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpsb2lh09r']
[2025-08-20T17:47:24.553+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask dvc_pull_data
[2025-08-20T17:47:24.976+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.dvc_pull_data scheduled__2025-08-19T00:00:00+00:00 [running]> on host bd9202be787f
[2025-08-20T17:47:25.711+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T00:00:00+00:00'
[2025-08-20T17:47:25.727+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-20T17:47:25.730+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && dvc pull --allow-missing || echo "DVC pull completed with missing files - continuing"']
[2025-08-20T17:47:25.789+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T17:47:33.935+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[2025-08-20T17:47:34.640+0000] {subprocess.py:93} INFO - DVC pull completed with missing files - continuing
[2025-08-20T17:47:34.642+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-20T17:47:34.770+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=dvc_pull_data, execution_date=20250819T000000, start_date=20250820T174724, end_date=20250820T174734
[2025-08-20T17:47:34.896+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-20T17:47:35.041+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
