[2025-08-18T21:22:58.810+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.model_training manual__2025-08-18T21:22:19.969882+00:00 [queued]>
[2025-08-18T21:22:58.822+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.model_training manual__2025-08-18T21:22:19.969882+00:00 [queued]>
[2025-08-18T21:22:58.823+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-18T21:22:58.841+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): model_training> on 2025-08-18 21:22:19.969882+00:00
[2025-08-18T21:22:58.847+0000] {standard_task_runner.py:60} INFO - Started process 2466 to run task
[2025-08-18T21:22:58.852+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'model_training', 'manual__2025-08-18T21:22:19.969882+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmp0vnppp_g']
[2025-08-18T21:22:58.855+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask model_training
[2025-08-18T21:22:58.930+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.model_training manual__2025-08-18T21:22:19.969882+00:00 [running]> on host 2e4674d7276b
[2025-08-18T21:22:59.035+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T21:22:19.969882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T21:22:19.969882+00:00'
[2025-08-18T21:22:59.037+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T21:22:59.039+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && python src/train_model.py']
[2025-08-18T21:22:59.052+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T21:23:01.246+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,244 WARNING Malformed experiment '3c451db2cddf461b9fa24b573ecdc116'. Detailed error Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/3c451db2cddf461b9fa24b573ecdc116/meta.yaml' does not exist.
[2025-08-18T21:23:01.247+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-18T21:23:01.248+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 327, in search_experiments
[2025-08-18T21:23:01.248+0000] {subprocess.py:93} INFO -     exp = self._get_experiment(exp_id, view_type)
[2025-08-18T21:23:01.249+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 421, in _get_experiment
[2025-08-18T21:23:01.249+0000] {subprocess.py:93} INFO -     meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
[2025-08-18T21:23:01.250+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1367, in _read_yaml
[2025-08-18T21:23:01.250+0000] {subprocess.py:93} INFO -     return _read_helper(root, file_name, attempts_remaining=retries)
[2025-08-18T21:23:01.251+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1360, in _read_helper
[2025-08-18T21:23:01.251+0000] {subprocess.py:93} INFO -     result = read_yaml(root, file_name)
[2025-08-18T21:23:01.252+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 309, in read_yaml
[2025-08-18T21:23:01.252+0000] {subprocess.py:93} INFO -     raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
[2025-08-18T21:23:01.253+0000] {subprocess.py:93} INFO - mlflow.exceptions.MissingConfigException: Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/3c451db2cddf461b9fa24b573ecdc116/meta.yaml' does not exist.
[2025-08-18T21:23:01.305+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,304 WARNING Malformed experiment '9f8a2292aea24d39a6b035889d38fb72'. Detailed error Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/9f8a2292aea24d39a6b035889d38fb72/meta.yaml' does not exist.
[2025-08-18T21:23:01.306+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-18T21:23:01.307+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 327, in search_experiments
[2025-08-18T21:23:01.308+0000] {subprocess.py:93} INFO -     exp = self._get_experiment(exp_id, view_type)
[2025-08-18T21:23:01.309+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 421, in _get_experiment
[2025-08-18T21:23:01.309+0000] {subprocess.py:93} INFO -     meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
[2025-08-18T21:23:01.310+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1367, in _read_yaml
[2025-08-18T21:23:01.311+0000] {subprocess.py:93} INFO -     return _read_helper(root, file_name, attempts_remaining=retries)
[2025-08-18T21:23:01.313+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1360, in _read_helper
[2025-08-18T21:23:01.314+0000] {subprocess.py:93} INFO -     result = read_yaml(root, file_name)
[2025-08-18T21:23:01.315+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 309, in read_yaml
[2025-08-18T21:23:01.316+0000] {subprocess.py:93} INFO -     raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
[2025-08-18T21:23:01.316+0000] {subprocess.py:93} INFO - mlflow.exceptions.MissingConfigException: Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/9f8a2292aea24d39a6b035889d38fb72/meta.yaml' does not exist.
[2025-08-18T21:23:01.318+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,318 WARNING Malformed experiment 'e45a2c3f2fe5435bb5ee5c51f9930955'. Detailed error Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/e45a2c3f2fe5435bb5ee5c51f9930955/meta.yaml' does not exist.
[2025-08-18T21:23:01.319+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-18T21:23:01.320+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 327, in search_experiments
[2025-08-18T21:23:01.320+0000] {subprocess.py:93} INFO -     exp = self._get_experiment(exp_id, view_type)
[2025-08-18T21:23:01.321+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 421, in _get_experiment
[2025-08-18T21:23:01.321+0000] {subprocess.py:93} INFO -     meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
[2025-08-18T21:23:01.322+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1367, in _read_yaml
[2025-08-18T21:23:01.322+0000] {subprocess.py:93} INFO -     return _read_helper(root, file_name, attempts_remaining=retries)
[2025-08-18T21:23:01.323+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1360, in _read_helper
[2025-08-18T21:23:01.323+0000] {subprocess.py:93} INFO -     result = read_yaml(root, file_name)
[2025-08-18T21:23:01.324+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 309, in read_yaml
[2025-08-18T21:23:01.324+0000] {subprocess.py:93} INFO -     raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
[2025-08-18T21:23:01.324+0000] {subprocess.py:93} INFO - mlflow.exceptions.MissingConfigException: Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/e45a2c3f2fe5435bb5ee5c51f9930955/meta.yaml' does not exist.
[2025-08-18T21:23:01.383+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,382 WARNING Malformed experiment '3c451db2cddf461b9fa24b573ecdc116'. Detailed error Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/3c451db2cddf461b9fa24b573ecdc116/meta.yaml' does not exist.
[2025-08-18T21:23:01.384+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-18T21:23:01.385+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 327, in search_experiments
[2025-08-18T21:23:01.386+0000] {subprocess.py:93} INFO -     exp = self._get_experiment(exp_id, view_type)
[2025-08-18T21:23:01.387+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 421, in _get_experiment
[2025-08-18T21:23:01.387+0000] {subprocess.py:93} INFO -     meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
[2025-08-18T21:23:01.388+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1367, in _read_yaml
[2025-08-18T21:23:01.389+0000] {subprocess.py:93} INFO -     return _read_helper(root, file_name, attempts_remaining=retries)
[2025-08-18T21:23:01.390+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1360, in _read_helper
[2025-08-18T21:23:01.390+0000] {subprocess.py:93} INFO -     result = read_yaml(root, file_name)
[2025-08-18T21:23:01.390+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 309, in read_yaml
[2025-08-18T21:23:01.391+0000] {subprocess.py:93} INFO -     raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
[2025-08-18T21:23:01.392+0000] {subprocess.py:93} INFO - mlflow.exceptions.MissingConfigException: Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/3c451db2cddf461b9fa24b573ecdc116/meta.yaml' does not exist.
[2025-08-18T21:23:01.452+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,451 WARNING Malformed experiment '9f8a2292aea24d39a6b035889d38fb72'. Detailed error Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/9f8a2292aea24d39a6b035889d38fb72/meta.yaml' does not exist.
[2025-08-18T21:23:01.453+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-18T21:23:01.454+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 327, in search_experiments
[2025-08-18T21:23:01.455+0000] {subprocess.py:93} INFO -     exp = self._get_experiment(exp_id, view_type)
[2025-08-18T21:23:01.456+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 421, in _get_experiment
[2025-08-18T21:23:01.456+0000] {subprocess.py:93} INFO -     meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
[2025-08-18T21:23:01.457+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1367, in _read_yaml
[2025-08-18T21:23:01.458+0000] {subprocess.py:93} INFO -     return _read_helper(root, file_name, attempts_remaining=retries)
[2025-08-18T21:23:01.459+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1360, in _read_helper
[2025-08-18T21:23:01.459+0000] {subprocess.py:93} INFO -     result = read_yaml(root, file_name)
[2025-08-18T21:23:01.460+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 309, in read_yaml
[2025-08-18T21:23:01.460+0000] {subprocess.py:93} INFO -     raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
[2025-08-18T21:23:01.461+0000] {subprocess.py:93} INFO - mlflow.exceptions.MissingConfigException: Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/9f8a2292aea24d39a6b035889d38fb72/meta.yaml' does not exist.
[2025-08-18T21:23:01.463+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,463 WARNING Malformed experiment 'e45a2c3f2fe5435bb5ee5c51f9930955'. Detailed error Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/e45a2c3f2fe5435bb5ee5c51f9930955/meta.yaml' does not exist.
[2025-08-18T21:23:01.464+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-18T21:23:01.465+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 327, in search_experiments
[2025-08-18T21:23:01.465+0000] {subprocess.py:93} INFO -     exp = self._get_experiment(exp_id, view_type)
[2025-08-18T21:23:01.465+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 421, in _get_experiment
[2025-08-18T21:23:01.466+0000] {subprocess.py:93} INFO -     meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
[2025-08-18T21:23:01.466+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1367, in _read_yaml
[2025-08-18T21:23:01.467+0000] {subprocess.py:93} INFO -     return _read_helper(root, file_name, attempts_remaining=retries)
[2025-08-18T21:23:01.468+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/file_store.py", line 1360, in _read_helper
[2025-08-18T21:23:01.468+0000] {subprocess.py:93} INFO -     result = read_yaml(root, file_name)
[2025-08-18T21:23:01.469+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 309, in read_yaml
[2025-08-18T21:23:01.469+0000] {subprocess.py:93} INFO -     raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
[2025-08-18T21:23:01.470+0000] {subprocess.py:93} INFO - mlflow.exceptions.MissingConfigException: Yaml file '/opt/***/Customer_Churn_Prediction_Pipeline/mlruns/e45a2c3f2fe5435bb5ee5c51f9930955/meta.yaml' does not exist.
[2025-08-18T21:23:01.470+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,464 INFO Loading features and target from feature store...
[2025-08-18T21:23:01.471+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,465 INFO Connecting to SQLite DB at data/features/churn_features.db
[2025-08-18T21:23:01.478+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,478 INFO Available tables: ['churn_features']
[2025-08-18T21:23:01.728+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,728 INFO Retrieved 7032 rows and 36 columns from table churn_features
[2025-08-18T21:23:01.730+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,730 INFO Found target column 'Churn'. Processing...
[2025-08-18T21:23:01.731+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,730 INFO Raw target column stats:
[2025-08-18T21:23:01.732+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,730 INFO   - Type: float64
[2025-08-18T21:23:01.733+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,731 INFO   - Unique values: [-0.601663392508594, 1.6620589061112205]
[2025-08-18T21:23:01.734+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,732 INFO   - Value counts:
[2025-08-18T21:23:01.734+0000] {subprocess.py:93} INFO - -0.601663    5163
[2025-08-18T21:23:01.735+0000] {subprocess.py:93} INFO -  1.662059    1869
[2025-08-18T21:23:01.735+0000] {subprocess.py:93} INFO - Name: Churn, dtype: int64
[2025-08-18T21:23:01.736+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,732 INFO Original target values before normalization: -0.601663    5163
[2025-08-18T21:23:01.736+0000] {subprocess.py:93} INFO -  1.662059    1869
[2025-08-18T21:23:01.737+0000] {subprocess.py:93} INFO - Name: Churn, dtype: int64
[2025-08-18T21:23:01.738+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,732 INFO Original target dtype: float64
[2025-08-18T21:23:01.739+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,733 INFO Unique numeric values in target: [-0.601663392508594, 1.6620589061112205]
[2025-08-18T21:23:01.740+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,733 INFO Binary target with values [-0.601663392508594, 1.6620589061112205]. Mapping to (0,1).
[2025-08-18T21:23:01.740+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,733 INFO Mapped -0.601663392508594→0, 1.6620589061112205→1
[2025-08-18T21:23:01.741+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,734 INFO Final normalized target stats:
[2025-08-18T21:23:01.742+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,734 INFO   - Unique values: [0, 1]
[2025-08-18T21:23:01.742+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,734 INFO   - Value counts:
[2025-08-18T21:23:01.743+0000] {subprocess.py:93} INFO - 0    5163
[2025-08-18T21:23:01.743+0000] {subprocess.py:93} INFO - 1    1869
[2025-08-18T21:23:01.744+0000] {subprocess.py:93} INFO - Name: Churn, dtype: int64
[2025-08-18T21:23:01.744+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,734 INFO Features shape before dtype fix: (7032, 35), Target shape: (7032,)
[2025-08-18T21:23:01.745+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,745 INFO Features dtypes after fix:
[2025-08-18T21:23:01.746+0000] {subprocess.py:93} INFO - gender                                   float64
[2025-08-18T21:23:01.746+0000] {subprocess.py:93} INFO - SeniorCitizen                            float64
[2025-08-18T21:23:01.747+0000] {subprocess.py:93} INFO - Partner                                  float64
[2025-08-18T21:23:01.747+0000] {subprocess.py:93} INFO - Dependents                               float64
[2025-08-18T21:23:01.748+0000] {subprocess.py:93} INFO - tenure                                   float64
[2025-08-18T21:23:01.749+0000] {subprocess.py:93} INFO - PhoneService                             float64
[2025-08-18T21:23:01.749+0000] {subprocess.py:93} INFO - PaperlessBilling                         float64
[2025-08-18T21:23:01.750+0000] {subprocess.py:93} INFO - MonthlyCharges                           float64
[2025-08-18T21:23:01.750+0000] {subprocess.py:93} INFO - TotalCharges                             float64
[2025-08-18T21:23:01.751+0000] {subprocess.py:93} INFO - TotalChargesPerTenure                    float64
[2025-08-18T21:23:01.751+0000] {subprocess.py:93} INFO - MultipleLines_No phone service           float64
[2025-08-18T21:23:01.752+0000] {subprocess.py:93} INFO - MultipleLines_Yes                        float64
[2025-08-18T21:23:01.752+0000] {subprocess.py:93} INFO - InternetService_Fiber optic              float64
[2025-08-18T21:23:01.753+0000] {subprocess.py:93} INFO - InternetService_No                       float64
[2025-08-18T21:23:01.754+0000] {subprocess.py:93} INFO - OnlineSecurity_No internet service       float64
[2025-08-18T21:23:01.754+0000] {subprocess.py:93} INFO - OnlineSecurity_Yes                       float64
[2025-08-18T21:23:01.755+0000] {subprocess.py:93} INFO - OnlineBackup_No internet service         float64
[2025-08-18T21:23:01.755+0000] {subprocess.py:93} INFO - OnlineBackup_Yes                         float64
[2025-08-18T21:23:01.756+0000] {subprocess.py:93} INFO - DeviceProtection_No internet service     float64
[2025-08-18T21:23:01.756+0000] {subprocess.py:93} INFO - DeviceProtection_Yes                     float64
[2025-08-18T21:23:01.757+0000] {subprocess.py:93} INFO - TechSupport_No internet service          float64
[2025-08-18T21:23:01.757+0000] {subprocess.py:93} INFO - TechSupport_Yes                          float64
[2025-08-18T21:23:01.758+0000] {subprocess.py:93} INFO - StreamingTV_No internet service          float64
[2025-08-18T21:23:01.758+0000] {subprocess.py:93} INFO - StreamingTV_Yes                          float64
[2025-08-18T21:23:01.759+0000] {subprocess.py:93} INFO - StreamingMovies_No internet service      float64
[2025-08-18T21:23:01.759+0000] {subprocess.py:93} INFO - StreamingMovies_Yes                      float64
[2025-08-18T21:23:01.760+0000] {subprocess.py:93} INFO - Contract_One year                        float64
[2025-08-18T21:23:01.760+0000] {subprocess.py:93} INFO - Contract_Two year                        float64
[2025-08-18T21:23:01.761+0000] {subprocess.py:93} INFO - PaymentMethod_Credit card (automatic)    float64
[2025-08-18T21:23:01.761+0000] {subprocess.py:93} INFO - PaymentMethod_Electronic check           float64
[2025-08-18T21:23:01.762+0000] {subprocess.py:93} INFO - PaymentMethod_Mailed check               float64
[2025-08-18T21:23:01.763+0000] {subprocess.py:93} INFO - TenureGroup_13-24                        float64
[2025-08-18T21:23:01.763+0000] {subprocess.py:93} INFO - TenureGroup_25-48                        float64
[2025-08-18T21:23:01.764+0000] {subprocess.py:93} INFO - TenureGroup_49-60                        float64
[2025-08-18T21:23:01.764+0000] {subprocess.py:93} INFO - TenureGroup_61+                          float64
[2025-08-18T21:23:01.766+0000] {subprocess.py:93} INFO - dtype: object
[2025-08-18T21:23:01.766+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,745 INFO Loaded features shape: (7032, 35), target shape: (7032,)
[2025-08-18T21:23:01.766+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,745 INFO Unique classes in target: [0 1]
[2025-08-18T21:23:01.767+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,746 INFO Class distribution: [5163 1869]
[2025-08-18T21:23:01.767+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,746 INFO Original class distribution: {0: 5163, 1: 1869}
[2025-08-18T21:23:01.768+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,746 INFO Class imbalance is acceptable (ratio: 2.76). No resampling applied.
[2025-08-18T21:23:01.768+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,746 INFO Splitting data into train and test sets (80/20, stratified)...
[2025-08-18T21:23:01.769+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,749 INFO Train set class distribution: {0: 4130, 1: 1495}
[2025-08-18T21:23:01.769+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:01,749 INFO Test set class distribution: {0: 1033, 1: 374}
[2025-08-18T21:23:03.026+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:03,025 INFO Training Logistic Regression...
[2025-08-18T21:23:05.845+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:05,845 INFO Logistic Regression recall: 0.7807, accuracy: 0.7306, precision: 0.4958, f1: 0.6064
[2025-08-18T21:23:05.854+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:05,854 INFO Classification report:
[2025-08-18T21:23:05.855+0000] {subprocess.py:93} INFO -               precision    recall  f1-score   support
[2025-08-18T21:23:05.856+0000] {subprocess.py:93} INFO - 
[2025-08-18T21:23:05.857+0000] {subprocess.py:93} INFO -            0       0.90      0.71      0.80      1033
[2025-08-18T21:23:05.858+0000] {subprocess.py:93} INFO -            1       0.50      0.78      0.61       374
[2025-08-18T21:23:05.859+0000] {subprocess.py:93} INFO - 
[2025-08-18T21:23:05.860+0000] {subprocess.py:93} INFO -     accuracy                           0.73      1407
[2025-08-18T21:23:05.861+0000] {subprocess.py:93} INFO -    macro avg       0.70      0.75      0.70      1407
[2025-08-18T21:23:05.861+0000] {subprocess.py:93} INFO - weighted avg       0.79      0.73      0.75      1407
[2025-08-18T21:23:05.862+0000] {subprocess.py:93} INFO - 
[2025-08-18T21:23:06.870+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:06,870 INFO Training Random Forest Classifier...
[2025-08-18T21:23:07.879+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:07,879 INFO Random Forest recall: 0.4733, accuracy: 0.7953, precision: 0.6604, f1: 0.5514
[2025-08-18T21:23:07.890+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:07,890 INFO Classification report:
[2025-08-18T21:23:07.891+0000] {subprocess.py:93} INFO -               precision    recall  f1-score   support
[2025-08-18T21:23:07.892+0000] {subprocess.py:93} INFO - 
[2025-08-18T21:23:07.893+0000] {subprocess.py:93} INFO -            0       0.83      0.91      0.87      1033
[2025-08-18T21:23:07.893+0000] {subprocess.py:93} INFO -            1       0.66      0.47      0.55       374
[2025-08-18T21:23:07.894+0000] {subprocess.py:93} INFO - 
[2025-08-18T21:23:07.894+0000] {subprocess.py:93} INFO -     accuracy                           0.80      1407
[2025-08-18T21:23:07.895+0000] {subprocess.py:93} INFO -    macro avg       0.74      0.69      0.71      1407
[2025-08-18T21:23:07.895+0000] {subprocess.py:93} INFO - weighted avg       0.78      0.80      0.78      1407
[2025-08-18T21:23:07.896+0000] {subprocess.py:93} INFO - 
[2025-08-18T21:23:07.984+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:07,983 INFO Best model (LogisticRegression) saved to models/churn_model.pkl with recall 0.7807
[2025-08-18T21:23:12.886+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:407: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2025-08-18T21:23:12.888+0000] {subprocess.py:93} INFO -   warnings.warn(
[2025-08-18T21:23:12.889+0000] {subprocess.py:93} INFO - Registered model 'churn_model' already exists. Creating a new version of this model...
[2025-08-18T21:23:12.891+0000] {subprocess.py:93} INFO - Created version '4' of model 'churn_model'.
[2025-08-18T21:23:13.065+0000] {subprocess.py:93} INFO - Downloading artifacts:   0%|          | 0/7 [00:00<?, ?it/s]Downloading artifacts:  14%|█▍        | 1/7 [00:00<00:00, 127.27it/s]Downloading artifacts:  29%|██▊       | 2/7 [00:00<00:00, 244.17it/s]Downloading artifacts:  43%|████▎     | 3/7 [00:00<00:00, 353.35it/s]Downloading artifacts:  57%|█████▋    | 4/7 [00:00<00:00, 449.90it/s]Downloading artifacts:  71%|███████▏  | 5/7 [00:00<00:00, 551.13it/s]Downloading artifacts:  86%|████████▌ | 6/7 [00:00<00:00, 650.65it/s]Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 741.04it/s]Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 725.78it/s]
[2025-08-18T21:23:13.066+0000] {subprocess.py:93} INFO - 2025-08-18 21:23:13,064 INFO Best model run_id written to /tmp/best_run_id.txt
[2025-08-18T21:23:13.630+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-18T21:23:13.672+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=customer_churn_pipeline, task_id=model_training, execution_date=20250818T212219, start_date=20250818T212258, end_date=20250818T212313
[2025-08-18T21:23:13.706+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-18T21:23:13.736+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
