[2025-08-18T21:20:34.110+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_pipeline.model_evaluation manual__2025-08-18T21:19:20.974289+00:00 [queued]>
[2025-08-18T21:20:34.126+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_pipeline.model_evaluation manual__2025-08-18T21:19:20.974289+00:00 [queued]>
[2025-08-18T21:20:34.128+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-18T21:20:34.170+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): model_evaluation> on 2025-08-18 21:19:20.974289+00:00
[2025-08-18T21:20:34.178+0000] {standard_task_runner.py:60} INFO - Started process 2297 to run task
[2025-08-18T21:20:34.185+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_pipeline', 'model_evaluation', 'manual__2025-08-18T21:19:20.974289+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn_pipeline_dag.py', '--cfg-path', '/tmp/tmpr0t7ouyk']
[2025-08-18T21:20:34.190+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask model_evaluation
[2025-08-18T21:20:34.288+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_churn_pipeline.model_evaluation manual__2025-08-18T21:19:20.974289+00:00 [running]> on host 2e4674d7276b
[2025-08-18T21:20:34.443+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_pipeline' AIRFLOW_CTX_TASK_ID='model_evaluation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T21:19:20.974289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T21:19:20.974289+00:00'
[2025-08-18T21:20:34.446+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T21:20:34.448+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/Customer_Churn_Prediction_Pipeline && python src/evaluate_model.py']
[2025-08-18T21:20:34.462+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T21:20:34.512+0000] {subprocess.py:93} INFO - python: can't open file 'src/evaluate_model.py': [Errno 2] No such file or directory
[2025-08-18T21:20:34.516+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T21:20:34.534+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T21:20:34.540+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_churn_pipeline, task_id=model_evaluation, execution_date=20250818T211920, start_date=20250818T212034, end_date=20250818T212034
[2025-08-18T21:20:34.571+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 47 for task model_evaluation (Bash command failed. The command returned a non-zero exit code 2.; 2297)
[2025-08-18T21:20:34.603+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-18T21:20:34.640+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
